# Generated by Django 4.1.7 on 2023-03-01 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authors', '0002_author_user_alter_author_age_alter_author_name_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
