# Generated by Django 4.1.7 on 2023-03-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_manga_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='cover',
            field=models.ImageField(upload_to='manga/%Y/%m/%d/', verbose_name='Capa'),
        ),
    ]
