# Generated by Django 4.1.7 on 2023-03-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_evaluation_comment'),
    ]

    operations = [
        migrations.RunSQL(
            (
                'CREATE FUNCTION fn_avgRating(mangaID BIGINT) RETURNS NUMERIC LANGUAGE plpgsql AS $$ DECLARE Avg_rating numeric; BEGIN SELECT AVG(authors_evaluation.rating) INTO Avg_rating FROM authors_evaluation WHERE authors_evaluation.manga_id = mangaId; RETURN Avg_rating; END; $$;'
            ),
            ('DROP FUNCTION IF EXISTS fn_avgRating();')
        )
    ]
    