# Generated by Django 4.1.7 on 2023-03-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_auto_20230304_1513'),
    ]

    operations = [
        migrations.RunSQL(
            (
                'CREATE FUNCTION fn_topRatedMangas() RETURNS TABLE (top_manga_id BIGINT, top_manga_total NUMERIC, top_manga_title VARCHAR) LANGUAGE plpgsql AS $$ BEGIN RETURN QUERY SELECT DISTINCT authors_evaluation.manga_id, fn_avgRating(authors_evaluation.manga_id) AS total, authors_manga.title FROM authors_evaluation JOIN authors_manga ON authors_manga.id = authors_evaluation.manga_id ORDER BY total DESC LIMIT 5; END; $$;'
            ),
            ('DROP FUNCTION IF EXISTS fn_topRatedMangas();')
        )
    ]